#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'omo-r1mini-teleop','console_scripts','teleop_joy'
__requires__ = 'omo-r1mini-teleop'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('omo-r1mini-teleop', 'console_scripts', 'teleop_joy')()
    )
